name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
        docker build . \
          --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/home-container:latest \
          --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/home-container:$GITHUB_SHA && \
        docker push --all-tags docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/home-container \